# docker-compose.yml
version: "3.8"
services:
  # load balancer
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    depends_on:
      - boot_app_1
      - boot_app_2
  boot_app_1:
    build:
      dockerfile: Dockerfile
      context: .
    # 임의의 network를 지정하면 default에 대한 자동설정이 없어짐, 따로 지정해야함
    networks:
      - default
      - apm-network
  boot_app_2:
    build:
      dockerfile: Dockerfile
      context: .
    networks:
      - default
      - apm-network

networks:
  apm-network:
    # 해당 docker-compose 파일 기준으로 생성된 네트워크에서 외부로 연결
    # apm-server와 같은 네트워크로 묶기 위한 설정
    external:
      name: apm_env